plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.finpulse-engine'
version = '0.0.1-SNAPSHOT'
description = 'Backend for personal expense-tracking system'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter'


    // REST API (Spring MVC, Jackson, Tomcat)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA + Hibernate
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // PostgreSQL JDBC Driver
    runtimeOnly 'org.postgresql:postgresql:42.7.4'

    // Spring Security (JWT middleware depends on this)
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Actuator for health checks and monitoring
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

    // for JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'


}


tasks.named('test') {
	useJUnitPlatform()
}
