
# ===============================
# Server
# ===============================
spring.application.name=finpulse-engine
server.port=8055

# JWT config
jwt.secret=dc76e9f0c0006e8f919e0c515c66dbba3982f785
jwt.expiration-ms=86400000


# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/finpulse_db
spring.datasource.username=finpulse_backend_rw_user
spring.datasource.password=finpulse_backend_pass
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


