apiVersion: v1
kind: ConfigMap
metadata:
  name: finpulse-engine-config
  namespace: default
data:
  # Application Configuration
  SPRING_APPLICATION_NAME: "finpulse-engine"
  SERVER_PORT: "8055"
  
  # Database Configuration (non-sensitive configurations)
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
