apiVersion: v1
kind: Secret
metadata:
  name: finpulse-engine-secret
  namespace: default
type: Opaque
stringData:
  # JWT Configuration
  JWT_SECRET: "dc76e9f0c0006e8f919e0c515c66dbba3982f785"
  JWT_EXPIRATION_MS: "86400000"
  
  # Database Credentials
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/finpulse_db"
  SPRING_DATASOURCE_USERNAME: "some-user"
  SPRING_DATASOURCE_PASSWORD: "some-pass"
